services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_PUBLIC_POSTHOG_KEY: ${VITE_PUBLIC_POSTHOG_KEY}
        VITE_PUBLIC_POSTHOG_HOST: ${VITE_PUBLIC_POSTHOG_HOST}
    ports:
      - "5008:5008"
    environment:
      - NODE_ENV=production
      - PORT=5008
    env_file: "./.env"
    restart: unless-stopped
    volumes:
      - ./audio_cache:/usr/src/app/audio_cache
    # For development, you might want to uncomment these volumes
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
