/**
 * Boot smoke test: starts the real `server.ts` in a subprocess and talks to it over a
 * real socket.
 *
 * Every other server-side test here builds a small express app out of the pieces it wants
 * to exercise (see sessionRoutes.test.ts), which is the right shape for policy but leaves
 * one gap: nothing at all covers `server.ts` itself. It does a lot of work at import time —
 * `getEnvOrCrash` for five variables, `await`ed filesystem setup, the middleware stack — and
 * a mistake in any of it is a server that exits before it listens. CI would stay green; the
 * failure would show up at deploy.
 *
 * So this asserts the two things only a booted process can show:
 *   1. it starts, listens, and answers a request;
 *   2. static assets come back compressed, which depends on middleware *order* — a fact no
 *      unit test can see, and one that a later refactor moving `compression()` below
 *      `express.static` would silently undo.
 *
 * Deliberately hermetic: dummy credentials, LIVEKIT_* blanked so the live-audio supervisor
 * stays off, PostHog pointed at a dead port, and all persistent state in a temp dir. Nothing
 * here reaches the network or touches a developer's real session state.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { spawn, type ChildProcess } from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import type { AddressInfo } from 'node:net';
import { fileURLToPath } from 'node:url';

const repoRoot = path.dirname(fileURLToPath(import.meta.url));

/**
 * A JS asset to request. Written rather than taken from `dist/` so the test runs whether or
 * not the suite is preceded by a build (`npm test` runs before `npm run build` in CI), and
 * padded past compression's 1 KB threshold so a correct server has to compress it.
 */
const FIXTURE_NAME = 'server-boot-smoke-fixture.js';
const FIXTURE_BODY =
  `// generated by serverBoot.test.ts\n` +
  `export const lines = [\n` +
  Array.from({ length: 400 }, (_, i) => `  "block ${i}: the quick brown fox",`).join('\n') +
  `\n];\n`;

let child: ChildProcess | undefined;
let base: string;
let stateDir: string;
let fixturePath: string;

/** An ephemeral port, released before the child claims it. */
async function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const probe = net.createServer();
    probe.on('error', reject);
    probe.listen(0, '127.0.0.1', () => {
      const { port } = probe.address() as AddressInfo;
      probe.close(() => resolve(port));
    });
  });
}

/** Poll until the server answers, or the child dies, or we run out of patience. */
async function waitForBoot(url: string, proc: ChildProcess, timeoutMs: number, log: () => string) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (proc.exitCode !== null || proc.signalCode !== null) {
      throw new Error(`server exited before listening (code ${proc.exitCode}):\n${log()}`);
    }
    try {
      const res = await fetch(url);
      if (res.ok) return;
    } catch {
      // not up yet
    }
    await new Promise((r) => setTimeout(r, 100));
  }
  throw new Error(`server did not boot within ${timeoutMs}ms:\n${log()}`);
}

beforeAll(async () => {
  stateDir = await fs.mkdtemp(path.join(os.tmpdir(), 'server-boot-'));
  // `express.static("dist")` is resolved against the cwd, so the asset has to live in the
  // real dist dir. The name is unique to this test and it is removed in afterAll, so a
  // build sitting there is left alone.
  await fs.mkdir(path.join(repoRoot, 'dist'), { recursive: true });
  fixturePath = path.join(repoRoot, 'dist', FIXTURE_NAME);
  await fs.writeFile(fixturePath, FIXTURE_BODY);

  const port = await freePort();
  base = `http://127.0.0.1:${port}`;

  let output = '';
  child = spawn(process.execPath, ['server.ts'], {
    cwd: repoRoot,
    stdio: ['ignore', 'pipe', 'pipe'],
    env: {
      ...process.env,
      PORT: String(port),
      // Dummy credentials: nothing below calls out to any of these services at boot.
      GEMINI_API_KEY: 'test-key',
      ELEVENLABS_API_KEY: 'test-key',
      YSWEET_CONNECTION_STRING: 'ys://127.0.0.1:9',
      VITE_PUBLIC_POSTHOG_KEY: 'phc_test',
      // Discard port: the PostHog client batches in the background, and this way nothing
      // it queues can leave the machine.
      VITE_PUBLIC_POSTHOG_HOST: 'http://127.0.0.1:9',
      // Empty, not absent: `dotenv/config` in the child fills in only keys that are missing
      // from the environment, so blanking these is what keeps a developer's real .env from
      // switching on the LiveKit supervisor (and its outbound connections) mid-test.
      LIVEKIT_URL: '',
      LIVEKIT_API_KEY: '',
      LIVEKIT_API_SECRET: '',
      WRITE_KEYS: '',
      WRITE_AUTH_MODE: 'off',
      // Keep the pinned session and reviewed-translation library out of ./audio-cache.
      SESSION_REGISTRY_PATH: path.join(stateDir, 'current-session.json'),
      SLIDE_LIBRARY_PATH: path.join(stateDir, 'slide-library.json'),
    },
  });
  child.stdout?.on('data', (d) => (output += d));
  child.stderr?.on('data', (d) => (output += d));

  await waitForBoot(`${base}/api/config`, child, 45_000, () => output);
}, 60_000);

afterAll(async () => {
  if (child && child.exitCode === null) {
    child.kill('SIGKILL');
  }
  await fs.rm(fixturePath, { force: true });
  await fs.rm(stateDir, { recursive: true, force: true });
});

describe('server boot', () => {
  it('starts, listens, and serves a route', async () => {
    const res = await fetch(`${base}/api/config`);
    expect(res.status).toBe(200);
    expect(await res.json()).toEqual({
      posthogKey: 'phc_test',
      posthogHost: 'http://127.0.0.1:9',
    });
  });
});

describe('static asset compression', () => {
  it('gzips a JS asset when the client accepts gzip', async () => {
    const res = await fetch(`${base}/${FIXTURE_NAME}`, {
      headers: { 'Accept-Encoding': 'gzip' },
    });
    expect(res.status).toBe(200);
    expect(res.headers.get('content-encoding')).toBe('gzip');
    // fetch inflates for us: proof the compressed body is intact, not just labelled.
    expect(await res.text()).toBe(FIXTURE_BODY);
  });

  it('prefers brotli when the client offers it', async () => {
    const res = await fetch(`${base}/${FIXTURE_NAME}`, {
      headers: { 'Accept-Encoding': 'br, gzip' },
    });
    expect(res.headers.get('content-encoding')).toBe('br');
    expect(await res.text()).toBe(FIXTURE_BODY);
  });

  it('serves the asset uncompressed to a client that asks for identity', async () => {
    const res = await fetch(`${base}/${FIXTURE_NAME}`, {
      headers: { 'Accept-Encoding': 'identity' },
    });
    expect(res.headers.get('content-encoding')).toBeNull();
    expect(await res.text()).toBe(FIXTURE_BODY);
  });
});
